//.$file${.::table.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dpp.qm
// File:  ${.::table.cpp}
//
// This code has been generated by QM 5.1.0 <www.state-machine.com/qm/>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${.::table.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"
#include "dpp.hpp"
#include "bsp.hpp"
#include <iostream>

Q_DEFINE_THIS_FILE

// Active object class -------------------------------------------------------
//.$declare${AOs::Table} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace DPP {

//.${AOs::Table} .............................................................
class Table : public QP::QActive {
public:
    static Table inst;

private:
    uint8_t m_fork[N_PHILO];
    bool m_isHungry[N_PHILO];
    std::uint8_t m_food;
    bool m_isStarving[N_PHILO];
    bool m_isDead[N_PHILO];
    std::uint8_t m_max_food;

public:
    explicit Table() noexcept;
    virtual ~Table();

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(active);
    Q_STATE_DECL(serving);
    Q_STATE_DECL(paused);
};

} // namespace DPP
//.$enddecl${AOs::Table} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

namespace DPP {

// helper function to provide the RIGHT neighbour of a Philo[n]
inline uint8_t RIGHT(uint8_t const n) {
    return static_cast<uint8_t>((n + (N_PHILO - 1U)) % N_PHILO);
}

// helper function to provide the LEFT neighbour of a Philo[n]
inline uint8_t LEFT(uint8_t const n) {
    return static_cast<uint8_t>((n + 1U) % N_PHILO);
}

constexpr uint8_t FREE = static_cast<uint8_t>(0);
constexpr uint8_t USED = static_cast<uint8_t>(1);

constexpr char_t const * const THINKING = &"thinking"[0];
constexpr char_t const * const HUNGRY   = &"hungry  "[0];
constexpr char_t const * const EATING   = &"eating  "[0];
constexpr char_t const * const STARVING = &"starving"[0];
constexpr char_t const * const DEAD = &"dead"[0];

} // namespace DPP

//.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//. Check for the minimum required QP version
#if (QP_VERSION < 650U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpcpp version 6.5.0 or higher required
#endif
//.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//.$define${Shared::AO_Table} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace DPP {

//.${Shared::AO_Table} .......................................................
QP::QActive * const AO_Table = &Table::inst; // "opaque" pointer to Table AO

} // namespace DPP
//.$enddef${Shared::AO_Table} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//.$define${AOs::Table} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace DPP {

//.${AOs::Table} .............................................................
Table Table::inst;
//.${AOs::Table::Table} ......................................................
Table::Table() noexcept
  : QActive(&initial)
{
    m_max_food = 3;
    m_food = m_max_food;

    for (uint8_t n = 0U; n < N_PHILO; ++n) {
        m_fork[n] = FREE;
        m_isHungry[n] = false;
        m_isStarving[n] = false;
        m_isDead[n] = false;
    }
}

//.${AOs::Table::~Table} .....................................................
Table::~Table() {
    std::cerr << "\ndestructor called.\n\n";
}

//.${AOs::Table::SM} .........................................................
Q_STATE_DEF(Table, initial) {
    //.${AOs::Table::SM::initial}
    (void)e; // suppress the compiler warning about unused parameter

    QS_OBJ_DICTIONARY(&Table::inst);

    QS_SIG_DICTIONARY(DONE_SIG,      nullptr); // global signals
    QS_SIG_DICTIONARY(EAT_SIG,       nullptr);
    QS_SIG_DICTIONARY(PAUSE_SIG,     nullptr);
    QS_SIG_DICTIONARY(SERVE_SIG,     nullptr);
    QS_SIG_DICTIONARY(TEST_SIG,      nullptr);

    QS_SIG_DICTIONARY(HUNGRY_SIG,    this); // signal just for Table
    QS_SIG_DICTIONARY(STARVING_SIG,  this); // signal just for Table
    QS_SIG_DICTIONARY(DEAD_SIG,      this); // signal just for Table

    subscribe(DONE_SIG);
    subscribe(PAUSE_SIG);
    subscribe(SERVE_SIG);
    subscribe(TEST_SIG);

    m_food = 3;
    m_food = m_max_food;

    for (uint8_t n = 0U; n < N_PHILO; ++n) {
        m_fork[n] = FREE;
        m_isHungry[n] = false;
        m_isStarving[n] = false;
        m_isDead[n] = false;
        BSP::displayPhilStat(n, THINKING, m_food);
    }

    QS_FUN_DICTIONARY(&Table::active);
    QS_FUN_DICTIONARY(&Table::serving);
    QS_FUN_DICTIONARY(&Table::paused);

    return tran(&serving);
}
//.${AOs::Table::SM::active} .................................................
Q_STATE_DEF(Table, active) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::Table::SM::active::TEST}
        case TEST_SIG: {
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::Table::SM::active::EAT}
        case EAT_SIG: {
            Q_ERROR();
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//.${AOs::Table::SM::active::serving} ........................................
Q_STATE_DEF(Table, serving) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::Table::SM::active::serving}
        case Q_ENTRY_SIG: {
            for (uint8_t n = 0U; n < N_PHILO; ++n) { // give permissions to eat...
                if ( m_isDead[n] )
                {
                    continue;
                }
                if ( (m_isHungry[n] || m_isStarving[n])
                    && (m_food > 0)
                    && (m_fork[LEFT(n)] == FREE)
                    && (m_fork[n] == FREE))
                {
                    m_fork[LEFT(n)] = USED;
                    m_fork[n] = USED;
                    m_food--;
                    TableEvt *te = Q_NEW(TableEvt, EAT_SIG);
                    te->philoNum = n;
                    QP::QF::PUBLISH(te, this);
                    m_isHungry[n] = m_isStarving[n] = false;
                    BSP::displayPhilStat(n, EATING, m_food);
                }
            }
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::Table::SM::active::serving::HUNGRY}
        case HUNGRY_SIG: {
            uint8_t n = Q_EVT_CAST(TableEvt)->philoNum;
            BSP::displayPhilStat(n, HUNGRY, m_food);

            // phil ID must be in range and he must be not hungry and not starving and not dead
            Q_ASSERT((n < N_PHILO) && (!m_isHungry[n]) && (!m_isStarving[n]) && (!m_isDead[n]));

            uint8_t m = LEFT(n);
            //.${AOs::Table::SM::active::serving::HUNGRY::[bothfree]}
            if ((m_fork[m] == FREE) && (m_fork[n] == FREE) && (m_food > 0)) {
                m_fork[m] = USED;
                m_fork[n] = USED;
                m_food--;
                TableEvt *pe = Q_NEW(TableEvt, EAT_SIG);
                pe->philoNum = n;
                QP::QF::PUBLISH(pe, this);
                BSP::displayPhilStat(n, EATING, m_food);
                status_ = Q_RET_HANDLED;
            }
            //.${AOs::Table::SM::active::serving::HUNGRY::[else]}
            else {
                m_isStarving[n] = m_isHungry[n];
                m_isHungry[n] = true;

                status_ = Q_RET_HANDLED;
            }
            break;
        }
        //.${AOs::Table::SM::active::serving::DONE}
        case DONE_SIG: {
            uint8_t n = Q_EVT_CAST(TableEvt)->philoNum;
            // phil ID must be in range and he must be not hungry or hungry but not starving and definitely not dead
            Q_ASSERT((n < N_PHILO) && (!m_isDead[n]) && ((!m_isHungry[n]) || ((m_isHungry[n]) && (!m_isStarving[n]))) );


            uint8_t m = LEFT(n);
            // both forks of Phil[n] must be used
            Q_ASSERT((m_fork[n] == USED) && (m_fork[m] == USED) && (m_food < m_max_food));

            m_fork[m] = FREE;
            m_fork[n] = FREE;

            // Put more food in the dish.
            m_food++;

            BSP::displayPhilStat(n, THINKING, m_food);

            m = RIGHT(n); // check the right neighbor

            if ( (! m_isDead[m]) && (m_isHungry[m] || m_isStarving[m]) && (m_fork[m] == FREE) && (m_food == m_max_food)) {
                m_fork[n] = USED;
                m_fork[m] = USED;
                m_food--;
                m_isHungry[m] = m_isStarving[m] = false;
                TableEvt *pe = Q_NEW(TableEvt, EAT_SIG);
                pe->philoNum = m;
                QP::QF::PUBLISH(pe, this);
                BSP::displayPhilStat(m, EATING, m_food);
            }
            m = LEFT(n); // check the left neighbor
            n = LEFT(m); // left fork of the left neighbor
            if ( (! m_isDead[m]) && (m_isHungry[m] || m_isStarving[m]) && (m_fork[n] == FREE) && (m_food == m_max_food)) {
                m_fork[m] = USED;
                m_fork[n] = USED;
                m_food--;
                m_isHungry[m] = m_isStarving[m] = false;
                TableEvt *pe = Q_NEW(TableEvt, EAT_SIG);
                pe->philoNum = m;
                QP::QF::PUBLISH(pe, this);
                BSP::displayPhilStat(m, EATING, m_food);
            }
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::Table::SM::active::serving::EAT}
        case EAT_SIG: {
            Q_ERROR();
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::Table::SM::active::serving::PAUSE}
        case PAUSE_SIG: {
            status_ = tran(&paused);
            break;
        }
        //.${AOs::Table::SM::active::serving::STARVING}
        case STARVING_SIG: {
            uint8_t n = Q_EVT_CAST(TableEvt)->philoNum;
            BSP::displayPhilStat(n, STARVING, m_food);

            // phil ID must be in range and he must be hungry but not starving and definitely not dead.
            Q_ASSERT((n < N_PHILO) && (m_isHungry[n]) && (!m_isStarving[n]) && (!m_isDead[n]));

            uint8_t m = LEFT(n);
            //.${AOs::Table::SM::active::serving::STARVING::[bothfree]}
            if ((m_fork[m] == FREE) && (m_fork[n] == FREE) && (m_food > 0)) {
                m_isHungry[n] = m_isStarving[n];
                m_fork[m] = USED;
                m_fork[n] = USED;
                m_food--;
                TableEvt *pe = Q_NEW(TableEvt, EAT_SIG);
                pe->philoNum = n;
                QP::QF::PUBLISH(pe, this);
                BSP::displayPhilStat(n, EATING, m_food);
                status_ = Q_RET_HANDLED;
            }
            //.${AOs::Table::SM::active::serving::STARVING::[else]}
            else {
                m_isHungry[n] = m_isStarving[n];
                m_isStarving[n] = true;
                status_ = Q_RET_HANDLED;
            }
            break;
        }
        //.${AOs::Table::SM::active::serving::DEAD}
        case DEAD_SIG: {
            uint8_t n = Q_EVT_CAST(TableEvt)->philoNum;
            BSP::displayPhilStat(n, DEAD, m_food);

            // phil ID must be in range and he must be not hungry but starving and definitely not dead
            Q_ASSERT((n < N_PHILO) && (!m_isDead[n]));
            Q_ASSERT((n < N_PHILO) && (m_isStarving[n]));
            Q_ASSERT((n < N_PHILO) && (!m_isHungry[n]));

            m_isDead[n] = true;

            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&active);
            break;
        }
    }
    return status_;
}
//.${AOs::Table::SM::active::paused} .........................................
Q_STATE_DEF(Table, paused) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::Table::SM::active::paused}
        case Q_ENTRY_SIG: {
            BSP::displayPaused(1U);
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::Table::SM::active::paused}
        case Q_EXIT_SIG: {
            BSP::displayPaused(0U);
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::Table::SM::active::paused::SERVE}
        case SERVE_SIG: {
            status_ = tran(&serving);
            break;
        }
        //.${AOs::Table::SM::active::paused::HUNGRY}
        case HUNGRY_SIG: {
            uint8_t n = Q_EVT_CAST(TableEvt)->philoNum;
            // philo ID must be in range and he must be not hungry and not starving
            Q_ASSERT((n < N_PHILO) && (!m_isHungry[n]) && (!m_isStarving[n]));
            m_isStarving[n] = m_isHungry[n];
            m_isHungry[n] = true;
            BSP::displayPhilStat(n, HUNGRY, m_food);
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::Table::SM::active::paused::DONE}
        case DONE_SIG: {
            uint8_t n = Q_EVT_CAST(TableEvt)->philoNum;
            // phil ID must be in range and he must be not hungry and not starving
            Q_ASSERT((n < N_PHILO) && (!m_isHungry[n]) && (!m_isStarving[n]));

            BSP::displayPhilStat(n, THINKING, m_food);
            uint8_t m = LEFT(n);
            /* both forks of Phil[n] must be used */
            Q_ASSERT((m_fork[n] == USED) && (m_fork[m] == USED) && (m_food < m_max_food));

            m_fork[m] = FREE;
            m_fork[n] = FREE;
            m_food++;

            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::Table::SM::active::paused::STARVING}
        case STARVING_SIG: {
            uint8_t n = Q_EVT_CAST(TableEvt)->philoNum;
            // philo ID must be in range and he must be hungry but not starving
            Q_ASSERT((n < N_PHILO) && (m_isHungry[n]) && (!m_isStarving[n]));
            m_isHungry[n] = m_isStarving[n];
            m_isStarving[n] = true;
            BSP::displayPhilStat(n, STARVING, m_food);
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&active);
            break;
        }
    }
    return status_;
}

} // namespace DPP
//.$enddef${AOs::Table} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
